//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PCI3TIER.RC
//
#define IDC_PB_HELP                     9
#define IDD_NETWORK                     100
#define IDD_DEVICE                      101
#define IDD_DEVICE_POS                  101
#define IDD_DRVF_COLLECT                108
#define IDD_DRVF_MOTION                 108
#define IDD_DEVICE_INT                  109
#define IDC_E_ST_VEL                    110
#define IDD_DEVICE_IO                   110
#define IDC_E_MAX_VEL                   111
#define IDD_DRVF_SETGET                 111
#define IDC_E_ACCL                      112
#define IDD_DRVF_OTHERS                 112
#define IDC_E_TACCL                     113
#define IDD_DRVF_SETAXIS                113
#define IDC_E_TDECCL                    114
#define IDC_E_DECCL                     115
#define IDC_E_T1ACCL                    116
#define IDC_E_T1DECCL                   117
#define IDC_E_TSACCL                    118
#define IDC_E_TSDECCL                   119
#define IDC_CB_SIMULATE                 203
#define IDC_CO_ADDRESS                  205
#define IDC_RB_8_CHANNELS               208
#define IDC_RB_16_CHANNELS              209
#define IDC_RB_INPUT_READ_COS           214
#define IDC_RB_INPUT_READ_CYCLIC        215
#define IDC_RB_HWTEST_RW                217
#define IDC_RB_HWTEST_OFF               218
#define IDC_CO_LENGTH                   220
#define IDC_E_COMMAND                   221
#define IDC_E_WBUFFER                   222
#define IDC_E_WLENGTH                   223
#define IDC_E_RBUFFER                   224
#define IDC_E_RLENGTH                   225
#define IDC_E_STATUS                    226
#define IDC_E_ADDRESS                   227
#define IDC_E_RESULT                    228
#define IDC_E_TIMEOUT                   229
#define IDC_E_POS                       229
#define IDC_E_PCODE                     230
#define IDC_E_VALUE                     231
#define IDC_E_DDSTATUS                  232
#define IDC_CO_PCI_INDEX                301
#define IDC_CO_PCI_COUNT                302
#define IDC_C_AXIS_NO                   302
#define IDC_C_AXIS_FUNCTION             303
#define IDC_C_PULSE_OUTMODE             303
#define IDC_E_SET                       304
#define IDC_C_PULSE_INMODE              304
#define IDC_E_GET                       305
#define IDC_C_HOME_ORG                  305
#define IDC_E_RATIO                     306
#define IDC_SCALE                       307
#define IDC_CHECK2                      308
#define IDC_C_HOME_LAT                  309
#define IDC_C_INDEX_SIG                 310
#define IDC_C_HOME_MODE                 311
#define IDC_C_SDP_DIS                   312
#define IDC_C_SDP_ACT                   313
#define IDC_C_MAN_PULSE_INMODE          314
#define IDC_LIMIT                       315
#define IDC_ALARM                       316
#define IDC_HOME                        317
#define IDC_E_SETU16_1                  317
#define IDC_ONEMOVE                     318
#define IDC_E_GETU16                    318
#define IDC_READY                       319
#define IDC_E_SETU16_2                  319
#define IDC_C_ALM_SIG                   320
#define IDC_E_SETU16_3                  320
#define IDC_C_ALM_SIG2                  321
#define IDC_E_SETU16_4                  321
#define IDC_C_INP_SIG                   322
#define IDC_C_INP_SIG1                  323
#define IDS_CP_SOFTWARE_FAULT           1000
#define IDS_CP_TOO_MANY_DRIVERS         1001
#define IDS_CP_DRIVER_NOT_CONFIGURED    1002
#define IDS_CP_DEVICE_NOT_CONFIGURED    1003
#define IDS_CP_UNKNOWN_DEVICE           1004
#define IDS_CP_NO_DEVICES               1005
#define IDS_CP_NETPASS1_ERROR           1006
#define IDS_CP_UNKNOWN_ACCESS           1007
#define IDS_CP_NO_INPUTS                1008
#define IDS_CP_NO_OUTPUTS               1009
#define IDS_CP_NO_MEMORY                1010
#define IDS_CP_NETCONFIG_ID             1011
#define IDS_CP_NETCONFIG_VERS           1012
#define IDS_CP_NETCONFIG_DPADR          1013
#define IDS_CP_NETCONFIG_DPLEN          1014
#define IDS_CP_NETCONFIG_PORT           1015
#define IDS_CP_NETCONFIG_WATCHDOG       1016
#define IDS_CP_NETCONFIG_HWTEST         1017
#define IDS_CP_NETCONFIG_STOPSTATE      1018
#define IDS_CP_NETCONFIG_SIMULATE       1019
#define IDS_CP_NETCONFIG_BAUDRATE       1020
#define IDS_CP_NETCONFIG_IRQ            1021
#define IDS_CP_NETCONFIGSIZE            1022
#define IDS_CP_SAME_DPRADR              1023
#define IDS_CP_SAME_PORT                1024
#define IDS_CP_SAME_IRQ                 1025
#define IDS_CP_DEVCONFIG_NETID          1026
#define IDS_CP_DEVCONFIG_ID             1027
#define IDS_CP_DEVCONFIG_VERS           1028
#define IDS_CP_DEVCONFIG_OFFSET         1029
#define IDS_CP_DEVCONFIG_ADDRESS        1030
#define IDS_CP_DEVCONFIG_SIZE           1031
#define IDS_CP_DEVCONFIG_CRITICAL       1032
#define IDS_CP_DEVCONFIG_FILE           1033
#define IDS_CP_DEVCONFIG_TYPE           1034
#define IDS_CP_DEVCONFIG_ERR            1035
#define IDS_CP_DEVCONFIG_INVALID_PCODE  1036
#define IDS_CP_OVERLAPP                 1040
#define IDS_CP_SAME_DP_ADDRESS          1041
#define IDS_CP_SAME_DEVICE_ADDRESS      1042
#define IDS_CP_DEVCONFIGFIELD           1043
#define IDS_CP_DEVCONFIGSIZE            1050
#define IDS_CP_CANNOT_GET_DEVCONFIG     1051
#define IDS_CP_CANNOT_GET_NETCONFIG     1052
#define IDS_CP_INVALID_PORT             1053
#define IDS_CP_INVALID_DPR              1054
#define IDS_CP_INVALID_STOPSTATE        1055
#define IDS_CP_INVALID_BAUDRATE         1056
#define IDS_CP_INVALID_POINT            1057
#define IDS_CP_POINT_OUTSIDE            1058
#define IDS_CP_INVALID_IRQLEVEL         1059
#define IDS_CP_POINT_OVERLAP            1060
#define IDS_CP_CANNOT_FIND_NETWORK      1061
#define IDS_CP_SAME_PCI_INDEX           1062
#define IDS_CP_INCONSISTENT_PCI_COUNT   1063
#define IDS_INVALID_PCI_INDEX           1064
#define IDS_INVALID_PCI_COUNT           1065
#define IDS_PCI_INDEX_TOO_BIG           1066
#define IDC_CO_POS                      2000
#define IDC_CO_INT                      2001
#define IDC_CO_IO                       2002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        801
#define _APS_NEXT_COMMAND_VALUE         4000
#define _APS_NEXT_CONTROL_VALUE         319
#define _APS_NEXT_SYMED_VALUE           2003
#endif
#endif
